@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQxNjEwNTh9._zPWOYNoF6YHixtemTe-7x31tJNNfBUeb35UCuVjQ-I

@hostname = http://localhost:3000

############# ACTORS ###############

### INDEX
GET {{hostname}}/actors

### CREATE

POST {{hostname}}/actors
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Casey",
  "last_name": "Cantrell",
  "known_for": "stuff",
  "age": 14
}

### SHOW

GET {{hostname}}/actors/2

### UPDATE

PATCH {{hostname}}/actors/5
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "age": "50"
}

### DESTROY


DELETE {{hostname}}/actors/8
Content-Type: application/json
Authorization: Bearer {{jwt}}


############# MOVIES ###############

### INDEX
GET {{hostname}}/movies

### CREATE

POST {{hostname}}/movies
Content-Type: application/json

{
  "title": "Casey's Cool Movie",
  "year": 1700,
  "plot": "Some stuff happens and it's crazy"
}

### SHOW

GET {{hostname}}/movies/21

### UPDATE

PATCH {{hostname}}/movies/2
Content-Type: application/json

{
  "year": 1979
}

### DESTROY

DELETE {{hostname}}/movies/21


####################### USERS

### CREATE (signup)
POST {{hostname}}/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "test",
  "password_confirmation": "test"
}

####################### SESSIONS
### CREATE (login)
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email": "casey@gmail.com",
  "password": "password"
}

########## MOVIE/GENRES

POST {{hostname}}/movie_genres
Content-Type: application/json

{
  "movie_id": 1,
  "genre_id": 1
}