############# ACTORS ###############

### INDEX
GET http://localhost:3000/actors

### CREATE

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Casey",
  "last_name": "Cantrell",
  "age": 1
}

### SHOW

GET http://localhost:3000/actors/2

### UPDATE

PATCH http://localhost:3000/actors/1
Content-Type: application/json

{
  "age": "42"
}

### DESTROY

DELETE http://localhost:3000/actors/24


############# MOVIES ###############

### INDEX
GET http://localhost:3000/movies

### CREATE

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Casey's Cool Movie",
  "year": 1700,
  "plot": "Some stuff happens and it's crazy"
}

### SHOW

GET http://localhost:3000/movies/2

### UPDATE

PATCH http://localhost:3000/movies/2
Content-Type: application/json

{
  "year": 1979
}

### DESTROY

DELETE http://localhost:3000/movies/18