@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE2NTQ4ODB9.XT62IhrErgIDQ5Imv0ZcWz1GsHCda8xjb4fgMyTkhAk

@hostname = http://localhost:3000

############# ACTORS ###############

### INDEX
GET {{hostname}}/actors

### CREATE

POST {{hostname}}/actors
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Casey",
  "last_name": "Cantrell",
  "age": 1
}

### SHOW

GET {{hostname}}/actors/2

### UPDATE

PATCH {{hostname}}/actors/1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "age": "42"
}

### DESTROY


DELETE {{hostname}}/actors/21
Content-Type: application/json
Authorization: Bearer {{jwt}}


############# MOVIES ###############

### INDEX
GET {{hostname}}/movies

### CREATE

POST {{hostname}}/movies
Content-Type: application/json

{
  "title": "Casey's Cool Movie",
  "year": 1700,
  "plot": "Some stuff happens and it's crazy"
}

### SHOW

GET {{hostname}}/movies/21

### UPDATE

PATCH {{hostname}}/movies/2
Content-Type: application/json

{
  "year": 1979
}

### DESTROY

DELETE {{hostname}}/movies/21


####################### USERS

### CREATE (signup)
POST {{hostname}}/users
Content-Type: application/json

{
  "name": "Quincy",
  "email": "quincy@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

####################### SESSIONS
### CREATE (login)
POST {{hostname}}/sessions
Content-Type: application/json

{
  "email": "casey@gmail.com",
  "password": "password"
}